"""create history

Revision ID: a289f20c0d0e
Revises: 77b147fe0ee2
Create Date: 2021-08-14 19:14:27.300885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a289f20c0d0e'
down_revision = '77b147fe0ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
